### ISSUE TITLE
Bank - banks api calls

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#15]
# Requirements
- Create a function to get a list of banks another bank has listed
- Create a function to set the trust level of a bank and return the response
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/banks

**Comment by jtavak** [comment]
Can I get #15 and #16

**Comment by jtavak** [comment]
Account number: 55bce9177483a0e4b1afc6f431c1f6104d3b84c6e6444fd978c33e9c031807bf

**Comment by tawanike** [comment]
Hi @MathClassIsTough, please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

**Comment by odetolataiwo** [comment]
@shahraizali paid.
