### ISSUE TITLE
Add Github Actions to automate testing and linting

### ISSUE THREAD

**Issue by CirXe0N** [thenewboston-developers/thenewboston-python-client#38]

**Comment by shahraizali** [comment]
Need to pay @CirXe0N for this. @sbalasa  you agree?

**Comment by sbalasa** [comment]
@shahraizali - this one to be paid to me

**Comment by tawanike** [comment]
Hi @sbalasa , please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

**Comment by sbalasa** [comment]
@tawanike - its d2131316a7286972bf15bfe914beac2fe56505a6b7a13aa3916a4f355736cbb3 thanks

**Comment by sbalasa** [comment]
![image](https://user-images.githubusercontent.com/4533119/99625676-b450e600-2a6b-11eb-8433-7c54f824b643.png)

**Comment by tawanike** [comment]
Paid
